module DogsHelper

  def dog_breeds
    [
        ['Affenpinscher'],
        ['Afghan Hound'],
        ['Airedale Terrier'],
        ['Akita'],
        ['Alaskan Malamute'],
        ['American Bulldog'],
        ['Connecticut', 'CT'],
        ['American Cocker Spaniel'],
        ['American Staffordshire Terrier'],
        ['American Water Spaniel'],
        ['Anatolian Shepherd Dog'],
        ['Appenzell Cattle Dog'],
        ['Australian Cattledog'],
        ['Australian Kelpie'],
        ['Australian Shepherd'],
        ['Australian Silky Terrier'],
        ['Australian Terrier'],
        ['Austrian Pinscher'],
        ['Azawakh'],
        ['Barsoi'],
        ['Basenji'],
        ['Bavarian Mountain Scenthound'],
        ['Beagle'],
        ['Bearded Collie'],
        ['Bedlington Terrier'],
        ['Belgian Shepherd Dog'],
        ['Bergamasco Shepherd'],
        ['Berger de Beauce'],
        ['Bernese Mountain Dog'],
        ['Bichon Frise'],
        ['Black and Tan Coonhound'],
        ['Bloodhound'],
        ['Boerboel'],
        ['Bohemian Wire-Haired Pointing Griffon'],
        ['Bolognese'],
        ['Border Collie'],
        ['Border Terrier'],
        ['Boston Terrier'],
        ['Bouvier des Ardennes'],
        ['Bouvier des Flandres'],
        ['Boxer'],
        ['Bracco Italiano'],
        ['Brazilian Terrier'],
        ['Briard'],
        ['Brittany Spaniel'],
        ['Bulldog'],
        ['Bullmastiff'],
        ['Bullterrier'],
        ['Cairn Terrier'],
        ['Cane Corso Italiano'],
        ['Catalonian Sheepdog'],
        ['Caucasian Shepherd Dog'],
        ['Cavalier King Charles Spaniel'],
        ['Cesky Terrier'],
        ['Chart Polski'],
        ['Chesapeake Bay Retriever'],
        ['Chihuahua'],
        ['Chinese Crested Dog'],
        ['Chodský pes'],
        ['Chow-Chow'],
        ['Cimarron Urugayo'],
        ['Clumber Spaniel'],
        ['Collie Rough'],
        ['Collie Smooth'],
        ['Coton de Tulear'],
        ['Croatian Sheepdog'],
        ['Curly Coated Retriever'],
        ['Czechoslovakian Wolfdog'],
        ['Cão da Serra de Aires'],
        ['Cão de Água Português'],
        ['Dachshund'],
        ['Dalmatian'],
        ['Dandie Dinmont Terrier'],
        ['Deerhound'],
        ['Dobermann'],
        ['Dogo Argentino'],
        ['Dogo Canario'],
        ['Dogue de Bordeaux'],
        ['Dutch Schapendoes'],
        ['Dutch Shepherd Dog'],
        ['East European Shepherd'],
        ['Englischer Pointer'],
        ['Englischer Setter'],
        ['English Cocker Spaniel'],
        ['English Springer Spaniel'],
        ['English Toy Terrier'],
        ['Entlebuch Cattle Dog'],
        ['Eurasian'],
        ['Field Spaniel'],
        ['Fila Brasileiro'],
        ['Flat Coated Retriever'],
        ['Foxterrier Smooth'],
        ['Foxterrier Wire'],
        ['French Bulldog'],
        ['French Water Dog'],
        ['Galgo Español'],
        ['German Hunting Terrier'],
        ['German Pinscher'],
        ['German Rough-haired Pointing Dog'],
        ['German Shepherd Dog'],
        ['German Short-haired Pointing Dog'],
        ['German Spaniel'],
        ['German Spitz'],
        ['German Wire-haired Pointer'],
        ['German long-haired Pointing Dog'],
        ['Giant Schnauzer'],
        ['Golden Retriever'],
        ['Gordon Setter'],
        ['Great Dane'],
        ['Great Swiss Mountain Dog'],
        ['Greyhound'],
        ['Griffon belge'],
        ['Griffon bruxellois'],
        ['Hanoverian Scenthound'],
        ['Havaneser'],
        ['Hokkaido'],
        ['Hovawart'],
        ['Hungarian Short-haired Pointing Dog'],
        ['Hungarian Wire-haired Pointing Dog'],
        ['Icelandic Sheepdog'],
        ['Irischer Glen of Imaal Terrier'],
        ['Irish Red Setter'],
        ['Irish Red and White Setter'],
        ['Irish Soft Coated Wheaten Terrier'],
        ['Irish Terrier'],
        ['Irish Water Spaniel'],
        ['Irish Wolfhound'],
        ['Italian Greyhound'],
        ['Italian Volpino'],
        ['Jack Russell Terrier'],
        ['Japanese Spitz'],
        ['Jämthund'],
        ['Kerry Blue Terrier'],
        ['Kleiner Münsterländer'],
        ['Komondor'],
        ['Kromfohrländer'],
        ['Kuvasz'],
        ['Labrador Retriever'],
        ['Lagotto Romagnolo'],
        ['Lakeland Terrier'],
        ['Landseer'],
        ['Lapponian Herder'],
        ['Large Munsterlander'],
        ['Leonberger'],
        ['Lhasa Apso'],
        ['Little Lion Dog'],
        ['Louisiana Catahoula Leoparden'],
        ['Magyar Agár'],
        ['Majorca Mastiff'],
        ['Maltese'],
        ['Manchester Terrier'],
        ['Maremma and the Abruzzes Sheepdog'],
        ['Mastiff'],
        ['Miniature Bull Terrier'],
        ['Miniature Pinscher'],
        ['Miniature Schnauzer'],
        ['Mixed breed'],
        ['Mudi'],
        ['Neapolitan Mastiff'],
        ['Nederlandse Kooikerhondje'],
        ['Newfoundland'],
        ['Norfolk Terrier'],
        ['Norwegian Buhund'],
        ['Norwich Terrier'],
        ['Nova Scotia Duck Tolling Retriever'],
        ['Ogar Polski'],
        ['Old English Sheepdog'],
        ['Old German Shepherd Dog'],
        ['Papillon'],
        ['Parson Russell Terrier'],
        ['Pekingese'],
        ['Petit Brabançon'],
        ['Phalène'],
        ['Pharaoh Hound'],
        ['Picardy Sheepdog'],
        ['Podengo Português'],
        ['Polish Lowland Sheepdog'],
        ['Poodle'],
        ['Prague Ratter'],
        ['Presa Canario'],
        ['Pudelpointer'],
        ['Pug'],
        ['Puli'],
        ['Pumi'],
        ['Pyrenean Mastiff'],
        ['Pyrenean Mountain Dog'],
        ['Rhodesian Ridgeback'],
        ['Rottweiler'],
        ['Russian Black Terrier'],
        ['Russkiy Toy'],
        ['Saarloos Wolfdog'],
        ['Saint Miguel Cattle Dog'],
        ['Saluki'],
        ['Samoyed'],
        ['Schipperke'],
        ['Schnauzer'],
        ['Scottish Terrier'],
        ['Sealyham Terrier'],
        ['Sharplanina'],
        ['Shetland Sheepdog'],
        ['Shiba'],
        ['Shih Tzu'],
        ['Siberian Husky'],
        ['Sloughi'],
        ['Slovakian Chuvach'],
        ['South Russian Shepherd Dog'],
        ['Spanish Waterdog'],
        ['Spinone'],
        ['St. Bernhard'],
        ['Staffordshire Bull Terrier'],
        ['Sussex Spaniel'],
        ['Thailand Ridgeback'],
        ['Tibet Spaniel'],
        ['Tibetan Mastiff'],
        ['Tibetan Terrier'],
        ['Tosa'],
        ['Weimaraner'],
        ['Welsh Corgi Cardigan'],
        ['Welsh Corgi Pembroke'],
        ['Welsh Springer Spaniel'],
        ['Welsh Terrier'],
        ['West Highland White Terrier'],
        ['Whippet'],
        ['White Swiss Shepherd Dog'],
        ['Working Kelpies'],
        ['Xoloitzcuintle'],
        ['Yorkshire Terrier']
    ]
  end
end